/**
 * Deploy `.env` shape — core vars required by the PHP API (see SlimApplicationFactory).
 * Traefik-only vars are optional and documented in comments.
 */

import type { GeneratedSecrets } from "./secrets.ts";

export const PLACEHOLDER = {
  DOMAIN: "REPLACE_WITH_YOUR_PUBLIC_DOMAIN",
  PUBLIC_BASE_URL: "REPLACE_WITH_HTTPS_ORIGIN_NO_TRAILING_SLASH",
  TUTOR_EMAIL: "REPLACE_WITH_TUTOR_INBOX_EMAIL",
  SMTP_HOST: "REPLACE_WITH_SMTP_HOST",
  SMTP_PORT: "587",
  MAIL_FROM: "REPLACE_WITH_MAIL_FROM_ADDRESS",
  REGISTRY_IMAGE: "ghcr.io/bastiion/tutor-certification",
  IMAGE_TAG: "REPLACE_WITH_RELEASE_TAG",
} as const;

export interface EnvFields {
  /** GitHub Container Registry image (lowercase), without tag */
  REGISTRY_IMAGE: string;
  /** Image tag, e.g. v0.1.0 */
  IMAGE_TAG: string;
  /** Public hostname (used by Traefik compose sample only) */
  DOMAIN: string;
  /** Optional Traefik external network name */
  TRAEFIK_NETWORK_NAME: string;
  TRAEFIK_ROUTER_NAME: string;
  TRAEFIK_ENTRYPOINT: string;
  TRAEFIK_CERT_RESOLVER: string;
  SERVER_BOX_KEYPAIR_BASE64: string;
  TOKEN_HMAC_KEY_BASE64: string;
  TUTOR_API_TOKEN: string;
  TUTOR_EMAIL: string;
  PUBLIC_BASE_URL: string;
  SMTP_HOST: string;
  SMTP_PORT: string;
  MAIL_FROM_ADDRESS: string;
  /** Optional: tls | ssl | empty — PHPMailer STARTTLS / SMTPS */
  SMTP_SECURE: string;
  /** Optional; both required if either set */
  SMTP_USER: string;
  SMTP_PASSWORD: string;
  /** Optional; comma-separated browser origins for CORS */
  CORS_ALLOWED_ORIGINS: string;
}

export function renderEnvFile(f: EnvFields): string {
  const lines: string[] = [
    `# Generated by env-wizard — review before production use.`,
    ``,
    `# --- Docker image (compose) ---`,
    `REGISTRY_IMAGE=${quoteIfNeeded(f.REGISTRY_IMAGE)}`,
    `IMAGE_TAG=${quoteIfNeeded(f.IMAGE_TAG)}`,
    ``,
    `# --- Traefik labels (only if you use deploy/docker-compose.traefik.yml) ---`,
    `DOMAIN=${quoteIfNeeded(f.DOMAIN)}`,
    `TRAEFIK_NETWORK_NAME=${quoteIfNeeded(f.TRAEFIK_NETWORK_NAME)}`,
    `TRAEFIK_ROUTER_NAME=${quoteIfNeeded(f.TRAEFIK_ROUTER_NAME)}`,
    `TRAEFIK_ENTRYPOINT=${quoteIfNeeded(f.TRAEFIK_ENTRYPOINT)}`,
    `TRAEFIK_CERT_RESOLVER=${quoteIfNeeded(f.TRAEFIK_CERT_RESOLVER)}`,
    ``,
    `# --- API secrets (required) ---`,
    `# libsodium crypto_box keypair 64 bytes (sk||pk), URL-safe Base64 without padding`,
    `SERVER_BOX_KEYPAIR_BASE64=${quoteIfNeeded(f.SERVER_BOX_KEYPAIR_BASE64)}`,
    `# 32-byte HMAC key for enrollment tokens, URL-safe Base64 without padding`,
    `TOKEN_HMAC_KEY_BASE64=${quoteIfNeeded(f.TOKEN_HMAC_KEY_BASE64)}`,
    `# Shared bearer for tutor routes (POST /api/sessions, POST /api/revocations)`,
    `TUTOR_API_TOKEN=${quoteIfNeeded(f.TUTOR_API_TOKEN)}`,
    ``,
    `# --- API runtime ---`,
    `TUTOR_EMAIL=${quoteIfNeeded(f.TUTOR_EMAIL)}`,
    `# Public origin for enrollment URLs from POST /api/sessions (no trailing slash)`,
    `PUBLIC_BASE_URL=${quoteIfNeeded(f.PUBLIC_BASE_URL)}`,
    `# Optional; leave empty if SPAs are same-origin as the API`,
    `CORS_ALLOWED_ORIGINS=${quoteIfNeeded(f.CORS_ALLOWED_ORIGINS)}`,
    ``,
    `SMTP_HOST=${quoteIfNeeded(f.SMTP_HOST)}`,
    `SMTP_PORT=${quoteIfNeeded(f.SMTP_PORT)}`,
    `MAIL_FROM_ADDRESS=${quoteIfNeeded(f.MAIL_FROM_ADDRESS)}`,
    `# Optional: empty | tls (STARTTLS, often 587) | ssl (SMTPS, often 465)`,
    `SMTP_SECURE=${quoteIfNeeded(f.SMTP_SECURE)}`,
    `# Optional: set both if your relay requires auth`,
    `SMTP_USER=${quoteIfNeeded(f.SMTP_USER)}`,
    `SMTP_PASSWORD=${quoteIfNeeded(f.SMTP_PASSWORD)}`,
    ``,
  ];

  return lines.join("\n");
}

function quoteIfNeeded(value: string): string {
  if (value === "") {
    return `""`;
  }
  if (/[\s#"$`!&|<>;()]/.test(value)) {
    const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `"${escaped}"`;
  }
  return value;
}

export function defaultEnvForAuto(secrets: GeneratedSecrets): EnvFields {
  return {
    REGISTRY_IMAGE: PLACEHOLDER.REGISTRY_IMAGE,
    IMAGE_TAG: PLACEHOLDER.IMAGE_TAG,
    DOMAIN: PLACEHOLDER.DOMAIN,
    TRAEFIK_NETWORK_NAME: "traefik",
    TRAEFIK_ROUTER_NAME: "bastiion-certs",
    TRAEFIK_ENTRYPOINT: "websecure",
    TRAEFIK_CERT_RESOLVER: "letsencrypt",
    SERVER_BOX_KEYPAIR_BASE64: secrets.SERVER_BOX_KEYPAIR_BASE64,
    TOKEN_HMAC_KEY_BASE64: secrets.TOKEN_HMAC_KEY_BASE64,
    TUTOR_API_TOKEN: secrets.TUTOR_API_TOKEN,
    TUTOR_EMAIL: PLACEHOLDER.TUTOR_EMAIL,
    PUBLIC_BASE_URL: PLACEHOLDER.PUBLIC_BASE_URL,
    SMTP_HOST: PLACEHOLDER.SMTP_HOST,
    SMTP_PORT: PLACEHOLDER.SMTP_PORT,
    MAIL_FROM_ADDRESS: PLACEHOLDER.MAIL_FROM,
    SMTP_SECURE: "",
    SMTP_USER: "",
    SMTP_PASSWORD: "",
    CORS_ALLOWED_ORIGINS: "",
  };
}
